"""init db

Revision ID: ecef8d1ec7d2
Revises: 
Create Date: 2020-05-04 06:44:53.508520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecef8d1ec7d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('publisher', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('content', sa.String(length=5000), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('sentiment_magnitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_article_date'), 'article', ['date'], unique=False)
    op.create_index(op.f('ix_article_publisher'), 'article', ['publisher'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_category'), 'category', ['category'], unique=True)
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_phrase'), 'topic', ['phrase'], unique=True)
    op.create_table('Category Classification',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], )
    )
    op.create_table('Topic Association',
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Topic Association')
    op.drop_table('Category Classification')
    op.drop_index(op.f('ix_topic_phrase'), table_name='topic')
    op.drop_table('topic')
    op.drop_index(op.f('ix_category_category'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_article_publisher'), table_name='article')
    op.drop_index(op.f('ix_article_date'), table_name='article')
    op.drop_table('article')
    # ### end Alembic commands ###
